### ISSUE TITLE
CI is not executed to a pull request

### ISSUE THREAD

**Issue by sago35** [conejoninja/tinyfont#17]
I want to run a CI test for #16.
CI test was added in #9, but it looks like it's probably not running against PR.

https://app.circleci.com/pipelines/github/tinygo-org/tinyfont

**Comment by sago35** [comment]
hi @deadprogram 

Maybe you need to set up the following.
I think it's probably enabled on tinygo-org/tinygo.

> By default, CircleCI does not build PRs from forked repositories. To change this setting, go to the Project Settings>Advanced of your project and set the Build forked pull requests option to On.

https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

**Comment by deadprogram** [comment]
Just turned on that setting for this repo as requested, @sago35 please let me know if it now works for you as expected.

**Comment by sago35** [comment]
@deadprogram 
Thank you.
CI appears to be working correctly.

https://github.com/tinygo-org/tinyfont/pull/24
https://app.circleci.com/pipelines/github/tinygo-org/tinyfont
