### ISSUE TITLE
Fonts have a severe impact on build times

### ISSUE THREAD

**Issue by timboldt** [conejoninja/tinyfont#22]
I imagine this is more of a compiler issue (?), but I think it is worth noting here.

It is frustrating that including TinyFonts increases build times by 10x or more.

A partial workaround is to copy the desired font into your project, but it generally means renaming packages to make it work. (Maybe TinyGo 0.14 helps, now that it has module support.)

**Comment by sago35** [comment]
I also get frustrated when building https://github.com/tinygo-org/tinyfont/blob/master/examples/pybadge/main.go on my windows laptop.

It might be better to use tinyfontgen on dev branch to create your own fonts.
You can use the bdf file as input to create a new font.
https://github.com/tinygo-org/tinyfont/tree/dev/cmd/tinyfontgen

**Comment by sago35** [comment]
source: https://github.com/tinygo-org/tinyfont/commit/c5a301ba5c68fdebfcc94d01d3d596b3a0f367b3

ubuntu 20.04
ryzen 3700

```
$ git rev-parse HEAD
c5a301ba5c68fdebfcc94d01d3d596b3a0f367b3

$ time tinygo build -o app.hex --target wioterminal --size short ./examples/displays
   code    data     bss |   flash     ram
  11712   32692    6364 |   44404   39056

real    0m13.646s
user    0m16.695s
sys     0m0.595s
```

windows 10 (git-bash)
core i7-7600U

```
$ git rev-parse HEAD
c5a301ba5c68fdebfcc94d01d3d596b3a0f367b3

$ time tinygo build -o app.hex --target wioterminal --size short ./examples/displays/
   code    data     bss |   flash     ram
  11696   32692    6364 |   44388   39056

real    0m54.952s
user    0m0.000s
sys     0m0.015s
```

**Comment by deadprogram** [comment]
TinyGo caches things a lot better these days. Also compiler is faster overall than it was. Can we close this issue now in favor of new ones as needed?

**Comment by conejoninja** [comment]
I vote for closing inactive issues, we could take a look at this : 
https://docs.github.com/en/github-ae@latest/actions/managing-issues-and-pull-requests/closing-inactive-issues

And close them by being inactive for X months (instead of days as proposed in the link).
In case this is still an issue (after almost three years) it could be reopened.

**Comment by sago35** [comment]
With the latest version, the build finishes in 11 seconds even without a cache. If the cache is present, it takes just 4 seconds. I believe this issue is no longer a problem.

```
$ git log -n1
commit cba4856f0e9917409bd809cfcf405228b3a2589b (HEAD -> dev, tag: v0.5.0, origin/release, origin/dev, origin/HEAD)
Author: deadprogram <ron@hybridgroup.com>
Date:   Wed Oct 30 18:27:52 2024 +0100

    modules: update to drivers 0.29.0

    Signed-off-by: deadprogram <ron@hybridgroup.com>

$ tinygo clean

$ go clean

$ tinygo version
tinygo version 0.35.0-dev-3b806217 windows/amd64 (using go version go1.23.2 and LLVM version 18.1.2)

$ time tinygo build -o app.hex --target wioterminal --size short ./examples/displays
   code    data     bss |   flash     ram
  12580   30780    6688 |   43360   37468

real    0m11.018s
user    0m0.000s
sys     0m0.000s
```

cached:

```
$ time tinygo build -o app.hex --target wioterminal --size short ./examples/displays
   code    data     bss |   flash     ram
  12580   30780    6688 |   43360   37468

real    0m4.252s
user    0m0.015s
sys     0m0.000s
```

**Comment by deadprogram** [comment]
Thank you!
