### ISSUE TITLE
Add CI tests

### ISSUE THREAD

**Issue by deadprogram** [conejoninja/tinyfont#9]
They can just be smoke tests. Something that we can run via a `Makefile` would be best.

**Comment by sago35** [comment]
I added a Makefile in #11 .

Memo: I haven't added any tests for the #10 sample yet

**Comment by sago35** [comment]
Hi @deadprogram 
It would be helpful if you could set up a CI.

**Comment by deadprogram** [comment]
The `dev` branch has CircleCI setup. Now closing this issue.
